services:
  rage-bot:
    # Для локальной сборки раскомментируйте 'build' и закомментируйте 'image'
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ghcr.io/feeldiference/rage_restart_bot:latest
    container_name: rage-restart-bot
    restart: unless-stopped

    # Запускаем от root для доступа к docker.sock
    # Внутри Dockerfile создается пользователь botuser, но здесь мы его переопределяем
    user: "0:0"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data

    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - TZ=Europe/Moscow
      - LOG_LEVEL=INFO

    networks:
      - rage-network

networks:
  rage-network:
    driver: bridge
    name: rage-network
